export const textSizeMap: Record<string, number> = {
  'text-xs': 12,
  'text-sm': 14,
  'text-base': 16,
  'text-lg': 18,
  'text-xl': 20,
  'text-2xl': 24,
  'text-3xl': 30,
  'text-4xl': 36,
  'text-5xl': 48,
};

export const FILTER_TABS: string[] = ['All', 'Files', 'People', 'Chats', 'Lists'];

export type LinkTabData = {
  filter: 'Files' | 'People' | 'Chats' | 'Lists';
  heading: string;
  subheading: string[];
  href: string;
  icon: string;
  status?: 'active' | 'inactive' | 'warning';
};

const peopleIcons = [
  'https://www.svgrepo.com/show/428259/matureman1.svg',
  'https://www.svgrepo.com/show/428256/malecostume.svg',
  'https://www.svgrepo.com/show/428260/maturewoman.svg',
  'https://www.svgrepo.com/show/428258/girl.svg',
  'https://www.svgrepo.com/show/428261/matureman2.svg',
  'https://www.svgrepo.com/show/428264/supportmale.svg',
  'https://www.svgrepo.com/show/428262/supportfemale.svg',
  'https://www.svgrepo.com/show/428269/female.svg',
  'https://www.svgrepo.com/show/428270/boy.svg',
];

export const FILTER_DATA: LinkTabData[] = [
  {
    filter: 'Files',
    heading: 'report.docx',
    subheading: ['in documents', 'saved 4m ago'],
    href: 'https://example.com/files/report.docx',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'vacation_photo.jpeg',
    subheading: ['in images', 'updated 2d ago'],
    href: 'https://example.com/files/vacation_photo.jpeg',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'meeting_recording.mp4',
    subheading: ['in videos', 'saved yesterday'],
    href: 'https://example.com/files/meeting_recording.mp4',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'podcast_episode.mp3',
    subheading: ['in audios', 'saved 1w ago'],
    href: 'https://example.com/files/podcast_episode.mp3',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'budget.xlsx',
    subheading: ['in spreadsheets', 'updated 3h ago'],
    href: 'https://example.com/files/budget.xlsx',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'presentation.ppt',
    subheading: ['in presentations', 'saved 5d ago'],
    href: 'https://example.com/files/presentation.ppt',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'profile_picture.svg',
    subheading: ['in icons', 'updated 1m ago'],
    href: 'https://example.com/files/profile_picture.svg',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'audio_note.aac',
    subheading: ['in audios', 'saved 2w ago'],
    href: 'https://example.com/files/audio_note.aac',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'document.pdf',
    subheading: ['in documents', 'updated 4d ago'],
    href: 'https://example.com/files/document.pdf',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'video_clip.mov',
    subheading: ['in videos', 'saved 1h ago'],
    href: 'https://example.com/files/video_clip.mov',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'notes.txt',
    subheading: ['in texts', 'updated 3w ago'],
    href: 'https://example.com/files/notes.txt',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'family_photo.webp',
    subheading: ['in images', 'saved 5h ago'],
    href: 'https://example.com/files/family_photo.webp',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'concert_recording.wav',
    subheading: ['in audios', 'saved 3d ago'],
    href: 'https://example.com/files/concert_recording.wav',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'holiday_video.avi',
    subheading: ['in videos', 'updated 2w ago'],
    href: 'https://example.com/files/holiday_video.avi',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'project_plan.doc',
    subheading: ['in documents', 'saved yesterday'],
    href: 'https://example.com/files/project_plan.doc',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'company_logo.png',
    subheading: ['in images', 'updated 1w ago'],
    href: 'https://example.com/files/company_logo.png',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'soundtrack.mp3',
    subheading: ['in audios', 'saved 10d ago'],
    href: 'https://example.com/files/soundtrack.mp3',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'launch_video.mp4a',
    subheading: ['in videos', 'updated 5m ago'],
    href: 'https://example.com/files/launch_video.mp4a',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'summary.pptx',
    subheading: ['in presentations', 'saved 4w ago'],
    href: 'https://example.com/files/summary.pptx',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'design_sketch.heif',
    subheading: ['in images', 'saved 2d ago'],
    href: 'https://example.com/files/design_sketch.heif',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'meeting_minutes.docx',
    subheading: ['in documents', 'updated 1m ago'],
    href: 'https://example.com/files/meeting_minutes.docx',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'garden_photo.jpg',
    subheading: ['in images', 'saved 30m ago'],
    href: 'https://example.com/files/garden_photo.jpg',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'live_session.mkv',
    subheading: ['in videos', 'updated 6h ago'],
    href: 'https://example.com/files/live_session.mkv',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'tracklist.aac',
    subheading: ['in audios', 'saved 3w ago'],
    href: 'https://example.com/files/tracklist.aac',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'notes_backup.txt',
    subheading: ['in texts', 'updated 3h ago'],
    href: 'https://example.com/files/notes_backup.txt',
    icon: 'text',
  },

  {
    filter: 'Files',
    heading: 'tutorial_video.mov',
    subheading: ['in videos', 'updated 5d ago'],
    href: 'https://example.com/files/tutorial_video.mov',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'voice_note.mp3',
    subheading: ['in audios', 'saved 7w ago'],
    href: 'https://example.com/files/voice_note.mp3',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'meeting_agenda.pdf',
    subheading: ['in documents', 'updated 15d ago'],
    href: 'https://example.com/files/meeting_agenda.pdf',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'concert_photo.png',
    subheading: ['in images', 'saved 4h ago'],
    href: 'https://example.com/files/concert_photo.png',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'conference_call.mp4',
    subheading: ['in videos', 'updated 2m ago'],
    href: 'https://example.com/files/conference_call.mp4',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'playlist.wav',
    subheading: ['in audios', 'saved 11w ago'],
    href: 'https://example.com/files/playlist.wav',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'avatar_webp',
    subheading: ['in images', 'saved 10s ago'],
    href: 'https://example.com/files/avatar.webp',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'birthday_video.mp4',
    subheading: ['in videos', 'saved 9d ago'],
    href: 'https://example.com/files/birthday_video.mp4',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'lecture_audio.aac',
    subheading: ['in audios', 'updated 13h ago'],
    href: 'https://example.com/files/lecture_audio.aac',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'shopping_list.xlsx',
    subheading: ['in spreadsheets', 'saved 3h ago'],
    href: 'https://example.com/files/shopping_list.xlsx',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'team_presentation.ppt',
    subheading: ['in presentations', 'updated 7d ago'],
    href: 'https://example.com/files/team_presentation.ppt',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'logo_icon.svg',
    subheading: ['in icons', 'saved 14h ago'],
    href: 'https://example.com/files/logo_icon.svg',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'background_music.mp3',
    subheading: ['in audios', 'updated 2w ago'],
    href: 'https://example.com/files/background_music.mp3',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'clip_show.mov',
    subheading: ['in videos', 'saved 6w ago'],
    href: 'https://example.com/files/clip_show.mov',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'draft_notes.txt',
    subheading: ['in texts', 'updated 9h ago'],
    href: 'https://example.com/files/draft_notes.txt',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'event_photo.jpg',
    subheading: ['in images', 'saved 1d ago'],
    href: 'https://example.com/files/event_photo.jpg',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'gameplay_video.avi',
    subheading: ['in videos', 'updated 10d ago'],
    href: 'https://example.com/files/gameplay_video.avi',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'voice_message.wav',
    subheading: ['in audios', 'saved 8h ago'],
    href: 'https://example.com/files/voice_message.wav',
    icon: 'audio',
  },
  {
    filter: 'Files',
    heading: 'document_backup.pdf',
    subheading: ['in documents', 'updated 2w ago'],
    href: 'https://example.com/files/document_backup.pdf',
    icon: 'text',
  },
  {
    filter: 'Files',
    heading: 'nature_photo.png',
    subheading: ['in images', 'saved 3d ago'],
    href: 'https://example.com/files/nature_photo.png',
    icon: 'image',
  },
  {
    filter: 'Files',
    heading: 'sports_highlight.mp4',
    subheading: ['in videos', 'updated 14m ago'],
    href: 'https://example.com/files/sports_highlight.mp4',
    icon: 'video',
  },
  {
    filter: 'Files',
    heading: 'sound_effect.aac',
    subheading: ['in audios', 'saved 5w ago'],
    href: 'https://example.com/files/sound_effect.aac',
    icon: 'audio',
  },

  {
    filter: 'People',
    heading: 'Caroline A. Dribsson',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleIcons[0],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Adam Cadribean',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleIcons[1],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'James E. Watson',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[2],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Maria Gonzalez',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[3],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'John Abraham',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[4],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Sophia M. Taylor',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleIcons[5],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Michael Brown',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleIcons[6],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Isabella Lopez',
    subheading: ['Offline'],
    href: '#',
    icon: peopleIcons[7],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'William D. Smith',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[8],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Mia Johnson',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleIcons[0],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'David R. Garcia',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleIcons[1],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Olivia Marich',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[2],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Richard Moore',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[3],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Emily Davis',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[4],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Joseph Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleIcons[5],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Amelia Clark',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleIcons[6],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Charles Wilkinson',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleIcons[7],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Evelyn Anderson',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[8],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Thomas Rodriguez',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[0],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Abigail Wilson',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[1],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Liam Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleIcons[2],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Noah Lopez',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleIcons[3],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Emma Johnson',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[4],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Oliver Davis',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[5],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Amelia Smith',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[6],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Elijah Garcia',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleIcons[7],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Mason R. Brown',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleIcons[8],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Logan Smith',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[0],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Ella Wilson',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[1],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Ava Johnson',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleIcons[2],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'James T. Miller',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[3],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Victoria P. Sanchez',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[4],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Benjamin Reid',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[5],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Chloe Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleIcons[6],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Zachary C. Evans',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleIcons[7],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Natalie King',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleIcons[8],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Samuel P. Torres',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[0],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Lily Foster',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[1],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Jack R. Bell',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[2],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Maddison O. Gray',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleIcons[3],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Henry Black',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleIcons[4],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Hannah S. White',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[5],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Sebastian Collins',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[6],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Zoe Davis',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[7],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Caleb Murphy',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleIcons[8],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Ella M. Morgan',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[0],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Jackson Perry',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleIcons[1],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Grace Long Lee',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[2],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'David Reed',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[3],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Samantha Hughes',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleIcons[4],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Owen Howard',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleIcons[5],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Aria Bennett',
    subheading: ['Busy'],
    href: '#',
    icon: peopleIcons[6],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Eli Brooks',
    subheading: ['Online'],
    href: '#',
    icon: peopleIcons[7],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Maya Anderson',
    subheading: ['Available'],
    href: '#',
    icon: peopleIcons[8],
    status: 'active',
  },
];
