export const textSizeMap: Record<string, number> = {
  'text-xs': 12,
  'text-sm': 14,
  'text-base': 16,
  'text-lg': 18,
  'text-xl': 20,
  'text-2xl': 24,
  'text-3xl': 30,
  'text-4xl': 36,
  'text-5xl': 48,
};

export const FILTER_TABS: Array<'All' | 'Files' | 'People' | 'Chats' | 'Lists'> = [
  'All',
  'Files',
  'People',
  'Chats',
  'Lists',
];

export type LinkTabData = {
  id: number;
  filter: 'Files' | 'People' | 'Chats' | 'Lists' | 'All';
  heading: string;
  subheading: string[];
  href: string;
  icon: string;
  status?: 'active' | 'inactive' | 'warning';
};

const peopleIcons: string[] = [
  'https://www.svgrepo.com/show/428259/matureman1.svg',
  'https://www.svgrepo.com/show/428256/malecostume.svg',
  'https://www.svgrepo.com/show/428260/maturewoman.svg',
  'https://www.svgrepo.com/show/428258/girl.svg',
  'https://www.svgrepo.com/show/428261/matureman2.svg',
  'https://www.svgrepo.com/show/428264/supportmale.svg',
  'https://www.svgrepo.com/show/428262/supportfemale.svg',
  'https://www.svgrepo.com/show/428269/female.svg',
  'https://www.svgrepo.com/show/428270/boy.svg',
];

export const FILTER_DATA: LinkTabData[] = [
  {
    filter: 'Files',
    heading: 'design_sketch.heif',
    subheading: ['in images', 'saved 2d ago'],
    href: 'https://example.com/files/design_sketch.heif',
    icon: 'image',
    id: 0,
  },
  {
    filter: 'Files',
    heading: 'notes.txt',
    subheading: ['in texts', 'updated 3w ago'],
    href: 'https://example.com/files/notes.txt',
    icon: 'text',
    id: 1,
  },
  {
    filter: 'People',
    heading: 'Liam Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428260/maturewoman.svg',
    status: 'inactive',
    id: 2,
  },
  {
    filter: 'Files',
    heading: 'holiday_video.avi',
    subheading: ['in videos', 'updated 2w ago'],
    href: 'https://example.com/files/holiday_video.avi',
    icon: 'video',
    id: 3,
  },
  {
    filter: 'People',
    heading: 'David R. Garcia',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428256/malecostume.svg',
    status: 'warning',
    id: 4,
  },
  {
    filter: 'Files',
    heading: 'draft_notes.txt',
    subheading: ['in texts', 'updated 9h ago'],
    href: 'https://example.com/files/draft_notes.txt',
    icon: 'text',
    id: 5,
  },
  {
    filter: 'Files',
    heading: 'meeting_recording.mp4',
    subheading: ['in videos', 'saved yesterday'],
    href: 'https://example.com/files/meeting_recording.mp4',
    icon: 'video',
    id: 6,
  },
  {
    filter: 'People',
    heading: 'Grace Long Lee',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428260/maturewoman.svg',
    status: 'warning',
    id: 7,
  },
  {
    filter: 'Files',
    heading: 'sports_highlight.mp4',
    subheading: ['in videos', 'updated 14m ago'],
    href: 'https://example.com/files/sports_highlight.mp4',
    icon: 'video',
    id: 8,
  },
  {
    filter: 'People',
    heading: 'Oliver Davis',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428264/supportmale.svg',
    status: 'active',
    id: 9,
  },
  {
    filter: 'Files',
    heading: 'tutorial_video.mov',
    subheading: ['in videos', 'updated 5d ago'],
    href: 'https://example.com/files/tutorial_video.mov',
    icon: 'video',
    id: 10,
  },
  {
    filter: 'People',
    heading: 'Sophia M. Taylor',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428264/supportmale.svg',
    status: 'inactive',
    id: 11,
  },
  {
    filter: 'Files',
    heading: 'voice_note.mp3',
    subheading: ['in audios', 'saved 7w ago'],
    href: 'https://example.com/files/voice_note.mp3',
    icon: 'audio',
    id: 12,
  },
  {
    filter: 'People',
    heading: 'Richard Moore',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428258/girl.svg',
    status: 'active',
    id: 13,
  },
  {
    filter: 'Files',
    heading: 'podcast_episode.mp3',
    subheading: ['in audios', 'saved 1w ago'],
    href: 'https://example.com/files/podcast_episode.mp3',
    icon: 'audio',
    id: 14,
  },
  {
    filter: 'Files',
    heading: 'gameplay_video.avi',
    subheading: ['in videos', 'updated 10d ago'],
    href: 'https://example.com/files/gameplay_video.avi',
    icon: 'video',
    id: 15,
  },
  {
    filter: 'People',
    heading: 'Samuel P. Torres',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428259/matureman1.svg',
    status: 'active',
    id: 16,
  },
  {
    filter: 'People',
    heading: 'Chloe Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428262/supportfemale.svg',
    status: 'inactive',
    id: 17,
  },
  {
    filter: 'People',
    heading: 'Thomas Rodriguez',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428259/matureman1.svg',
    status: 'active',
    id: 18,
  },
  {
    filter: 'People',
    heading: 'John Abraham',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428261/matureman2.svg',
    status: 'active',
    id: 19,
  },
  {
    filter: 'People',
    heading: 'Hannah S. White',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428264/supportmale.svg',
    status: 'warning',
    id: 20,
  },
  {
    filter: 'Files',
    heading: 'launch_video.mp4a',
    subheading: ['in videos', 'updated 5m ago'],
    href: 'https://example.com/files/launch_video.mp4a',
    icon: 'video',
    id: 21,
  },
  {
    filter: 'People',
    heading: 'Logan Smith',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428259/matureman1.svg',
    status: 'warning',
    id: 22,
  },
  {
    filter: 'Files',
    heading: 'lecture_audio.aac',
    subheading: ['in audios', 'updated 13h ago'],
    href: 'https://example.com/files/lecture_audio.aac',
    icon: 'audio',
    id: 23,
  },
  {
    filter: 'Files',
    heading: 'document.pdf',
    subheading: ['in documents', 'updated 4d ago'],
    href: 'https://example.com/files/document.pdf',
    icon: 'text',
    id: 24,
  },
  {
    filter: 'Files',
    heading: 'vacation_photo.jpeg',
    subheading: ['in images', 'updated 2d ago'],
    href: 'https://example.com/files/vacation_photo.jpeg',
    icon: 'image',
    id: 25,
  },
  {
    filter: 'Files',
    heading: 'meeting_agenda.pdf',
    subheading: ['in documents', 'updated 15d ago'],
    href: 'https://example.com/files/meeting_agenda.pdf',
    icon: 'text',
    id: 26,
  },
  {
    filter: 'People',
    heading: 'Mason R. Brown',
    subheading: ['Unactivated'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428270/boy.svg',
    status: 'inactive',
    id: 27,
  },
  {
    filter: 'People',
    heading: 'Aria Bennett',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428262/supportfemale.svg',
    status: 'warning',
    id: 28,
  },
  {
    filter: 'Files',
    heading: 'concert_recording.wav',
    subheading: ['in audios', 'saved 3d ago'],
    href: 'https://example.com/files/concert_recording.wav',
    icon: 'audio',
    id: 29,
  },
  {
    filter: 'People',
    heading: 'Ava Johnson',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428260/maturewoman.svg',
    status: 'warning',
    id: 30,
  },
  {
    filter: 'People',
    heading: 'Mia Johnson',
    subheading: ['Unactivated'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428259/matureman1.svg',
    status: 'inactive',
    id: 31,
  },
  {
    filter: 'People',
    heading: 'Caleb Murphy',
    subheading: ['Unactivated'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428270/boy.svg',
    status: 'inactive',
    id: 32,
  },
  {
    filter: 'Files',
    heading: 'project_plan.doc',
    subheading: ['in documents', 'saved yesterday'],
    href: 'https://example.com/files/project_plan.doc',
    icon: 'text',
    id: 33,
  },
  {
    filter: 'Files',
    heading: 'budget.xlsx',
    subheading: ['in spreadsheets', 'updated 3h ago'],
    href: 'https://example.com/files/budget.xlsx',
    icon: 'text',
    id: 34,
  },
  {
    filter: 'Files',
    heading: 'report.docx',
    subheading: ['in documents', 'saved 4m ago'],
    href: 'https://example.com/files/report.docx',
    icon: 'text',
    id: 35,
  },
  {
    filter: 'Files',
    heading: 'live_session.mkv',
    subheading: ['in videos', 'updated 6h ago'],
    href: 'https://example.com/files/live_session.mkv',
    icon: 'video',
    id: 36,
  },
  {
    filter: 'People',
    heading: 'Charles Wilkinson',
    subheading: ['Unactivated'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428269/female.svg',
    status: 'inactive',
    id: 37,
  },
  {
    filter: 'Files',
    heading: 'company_logo.png',
    subheading: ['in images', 'updated 1w ago'],
    href: 'https://example.com/files/company_logo.png',
    icon: 'image',
    id: 38,
  },
  {
    filter: 'People',
    heading: 'Victoria P. Sanchez',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428261/matureman2.svg',
    status: 'warning',
    id: 39,
  },
  {
    filter: 'People',
    heading: 'James T. Miller',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428258/girl.svg',
    status: 'active',
    id: 40,
  },
  {
    filter: 'Files',
    heading: 'profile_picture.svg',
    subheading: ['in icons', 'updated 1m ago'],
    href: 'https://example.com/files/profile_picture.svg',
    icon: 'image',
    id: 41,
  },
  {
    filter: 'Files',
    heading: 'sound_effect.aac',
    subheading: ['in audios', 'saved 5w ago'],
    href: 'https://example.com/files/sound_effect.aac',
    icon: 'audio',
    id: 42,
  },
  {
    filter: 'People',
    heading: 'Adam Cadribean',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428256/malecostume.svg',
    status: 'warning',
    id: 43,
  },
  {
    filter: 'People',
    heading: 'Owen Howard',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428264/supportmale.svg',
    status: 'warning',
    id: 44,
  },
  {
    filter: 'People',
    heading: 'Emily Davis',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428261/matureman2.svg',
    status: 'active',
    id: 45,
  },
  {
    filter: 'People',
    heading: 'Caroline A. Dribsson',
    subheading: ['Unactivated'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428259/matureman1.svg',
    status: 'inactive',
    id: 46,
  },
  {
    filter: 'People',
    heading: 'Samantha Hughes',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428261/matureman2.svg',
    status: 'inactive',
    id: 47,
  },
  {
    filter: 'People',
    heading: 'Henry Black',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428261/matureman2.svg',
    status: 'warning',
    id: 48,
  },
  {
    filter: 'People',
    heading: 'Benjamin Reid',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428264/supportmale.svg',
    status: 'active',
    id: 49,
  },
  {
    filter: 'People',
    heading: 'Noah Lopez',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428258/girl.svg',
    status: 'warning',
    id: 50,
  },
  {
    filter: 'People',
    heading: 'Amelia Clark',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428262/supportfemale.svg',
    status: 'warning',
    id: 51,
  },
  {
    filter: 'People',
    heading: 'Joseph Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428264/supportmale.svg',
    status: 'inactive',
    id: 52,
  },
  {
    filter: 'Files',
    heading: 'presentation.ppt',
    subheading: ['in presentations', 'saved 5d ago'],
    href: 'https://example.com/files/presentation.ppt',
    icon: 'text',
    id: 53,
  },
  {
    filter: 'Files',
    heading: 'conference_call.mp4',
    subheading: ['in videos', 'updated 2m ago'],
    href: 'https://example.com/files/conference_call.mp4',
    icon: 'video',
    id: 54,
  },
  {
    filter: 'Files',
    heading: 'shopping_list.xlsx',
    subheading: ['in spreadsheets', 'saved 3h ago'],
    href: 'https://example.com/files/shopping_list.xlsx',
    icon: 'text',
    id: 55,
  },
  {
    filter: 'Files',
    heading: 'logo_icon.svg',
    subheading: ['in icons', 'saved 14h ago'],
    href: 'https://example.com/files/logo_icon.svg',
    icon: 'image',
    id: 56,
  },
  {
    filter: 'Files',
    heading: 'audio_note.aac',
    subheading: ['in audios', 'saved 2w ago'],
    href: 'https://example.com/files/audio_note.aac',
    icon: 'audio',
    id: 57,
  },
  {
    filter: 'Files',
    heading: 'team_presentation.ppt',
    subheading: ['in presentations', 'updated 7d ago'],
    href: 'https://example.com/files/team_presentation.ppt',
    icon: 'text',
    id: 58,
  },
  {
    filter: 'People',
    heading: 'Evelyn Anderson',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428270/boy.svg',
    status: 'warning',
    id: 59,
  },
  {
    filter: 'People',
    heading: 'William D. Smith',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428270/boy.svg',
    status: 'active',
    id: 60,
  },
  {
    filter: 'People',
    heading: 'Jack R. Bell',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428260/maturewoman.svg',
    status: 'active',
    id: 61,
  },
  {
    filter: 'Files',
    heading: 'concert_photo.png',
    subheading: ['in images', 'saved 4h ago'],
    href: 'https://example.com/files/concert_photo.png',
    icon: 'image',
    id: 62,
  },
  {
    filter: 'People',
    heading: 'Jackson Perry',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428256/malecostume.svg',
    status: 'warning',
    id: 63,
  },
  {
    filter: 'People',
    heading: 'Abigail Wilson',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428256/malecostume.svg',
    status: 'active',
    id: 64,
  },
  {
    filter: 'People',
    heading: 'Maddison O. Gray',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428258/girl.svg',
    status: 'inactive',
    id: 65,
  },
  {
    filter: 'People',
    heading: 'Olivia Marich',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428260/maturewoman.svg',
    status: 'warning',
    id: 66,
  },
  {
    filter: 'People',
    heading: 'Isabella Lopez',
    subheading: ['Offline'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428269/female.svg',
    status: 'inactive',
    id: 67,
  },
  {
    filter: 'People',
    heading: 'Natalie King',
    subheading: ['Unactivated'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428270/boy.svg',
    status: 'inactive',
    id: 68,
  },
  {
    filter: 'People',
    heading: 'Amelia Smith',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428262/supportfemale.svg',
    status: 'active',
    id: 69,
  },
  {
    filter: 'Files',
    heading: 'birthday_video.mp4',
    subheading: ['in videos', 'saved 9d ago'],
    href: 'https://example.com/files/birthday_video.mp4',
    icon: 'video',
    id: 70,
  },
  {
    filter: 'People',
    heading: 'Ella M. Morgan',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428259/matureman1.svg',
    status: 'active',
    id: 71,
  },
  {
    filter: 'Files',
    heading: 'avatar_webp',
    subheading: ['in images', 'saved 10s ago'],
    href: 'https://example.com/files/avatar.webp',
    icon: 'image',
    id: 72,
  },
  {
    filter: 'Files',
    heading: 'nature_photo.png',
    subheading: ['in images', 'saved 3d ago'],
    href: 'https://example.com/files/nature_photo.png',
    icon: 'image',
    id: 73,
  },
  {
    filter: 'Files',
    heading: 'family_photo.webp',
    subheading: ['in images', 'saved 5h ago'],
    href: 'https://example.com/files/family_photo.webp',
    icon: 'image',
    id: 74,
  },
  {
    filter: 'Files',
    heading: 'background_music.mp3',
    subheading: ['in audios', 'updated 2w ago'],
    href: 'https://example.com/files/background_music.mp3',
    icon: 'audio',
    id: 75,
  },
  {
    filter: 'Files',
    heading: 'document_backup.pdf',
    subheading: ['in documents', 'updated 2w ago'],
    href: 'https://example.com/files/document_backup.pdf',
    icon: 'text',
    id: 76,
  },
  {
    filter: 'People',
    heading: 'Eli Brooks',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428269/female.svg',
    status: 'active',
    id: 77,
  },
  {
    filter: 'People',
    heading: 'Maria Gonzalez',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428258/girl.svg',
    status: 'active',
    id: 78,
  },
  {
    filter: 'Files',
    heading: 'garden_photo.jpg',
    subheading: ['in images', 'saved 30m ago'],
    href: 'https://example.com/files/garden_photo.jpg',
    icon: 'image',
    id: 79,
  },
  {
    filter: 'People',
    heading: 'Ella Wilson',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428256/malecostume.svg',
    status: 'active',
    id: 80,
  },
  {
    filter: 'Files',
    heading: 'meeting_minutes.docx',
    subheading: ['in documents', 'updated 1m ago'],
    href: 'https://example.com/files/meeting_minutes.docx',
    icon: 'text',
    id: 81,
  },
  {
    filter: 'People',
    heading: 'Emma Johnson',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428261/matureman2.svg',
    status: 'warning',
    id: 82,
  },
  {
    filter: 'People',
    heading: 'Elijah Garcia',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428269/female.svg',
    status: 'warning',
    id: 83,
  },
  {
    filter: 'Files',
    heading: 'video_clip.mov',
    subheading: ['in videos', 'saved 1h ago'],
    href: 'https://example.com/files/video_clip.mov',
    icon: 'video',
    id: 84,
  },
  {
    filter: 'Files',
    heading: 'soundtrack.mp3',
    subheading: ['in audios', 'saved 10d ago'],
    href: 'https://example.com/files/soundtrack.mp3',
    icon: 'audio',
    id: 85,
  },
  {
    filter: 'Files',
    heading: 'notes_backup.txt',
    subheading: ['in texts', 'updated 3h ago'],
    href: 'https://example.com/files/notes_backup.txt',
    icon: 'text',
    id: 86,
  },
  {
    filter: 'People',
    heading: 'Zachary C. Evans',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428269/female.svg',
    status: 'warning',
    id: 87,
  },
  {
    filter: 'People',
    heading: 'Maya Anderson',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428270/boy.svg',
    status: 'active',
    id: 88,
  },
  {
    filter: 'Files',
    heading: 'tracklist.aac',
    subheading: ['in audios', 'saved 3w ago'],
    href: 'https://example.com/files/tracklist.aac',
    icon: 'audio',
    id: 89,
  },
  {
    filter: 'Files',
    heading: 'event_photo.jpg',
    subheading: ['in images', 'saved 1d ago'],
    href: 'https://example.com/files/event_photo.jpg',
    icon: 'image',
    id: 90,
  },
  {
    filter: 'Files',
    heading: 'summary.pptx',
    subheading: ['in presentations', 'saved 4w ago'],
    href: 'https://example.com/files/summary.pptx',
    icon: 'text',
    id: 91,
  },
  {
    filter: 'People',
    heading: 'David Reed',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428258/girl.svg',
    status: 'active',
    id: 92,
  },
  {
    filter: 'Files',
    heading: 'clip_show.mov',
    subheading: ['in videos', 'saved 6w ago'],
    href: 'https://example.com/files/clip_show.mov',
    icon: 'video',
    id: 93,
  },
  {
    filter: 'People',
    heading: 'Zoe Davis',
    subheading: ['Available'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428269/female.svg',
    status: 'active',
    id: 94,
  },
  {
    filter: 'People',
    heading: 'Michael Brown',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428262/supportfemale.svg',
    status: 'warning',
    id: 95,
  },
  {
    filter: 'People',
    heading: 'James E. Watson',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428260/maturewoman.svg',
    status: 'warning',
    id: 96,
  },
  {
    filter: 'Files',
    heading: 'playlist.wav',
    subheading: ['in audios', 'saved 11w ago'],
    href: 'https://example.com/files/playlist.wav',
    icon: 'audio',
    id: 97,
  },
  {
    filter: 'People',
    heading: 'Sebastian Collins',
    subheading: ['Online'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428262/supportfemale.svg',
    status: 'active',
    id: 98,
  },
  {
    filter: 'People',
    heading: 'Lily Foster',
    subheading: ['Busy'],
    href: '#',
    icon: 'https://www.svgrepo.com/show/428256/malecostume.svg',
    status: 'warning',
    id: 99,
  },
  {
    filter: 'Files',
    heading: 'voice_message.wav',
    subheading: ['in audios', 'saved 8h ago'],
    href: 'https://example.com/files/voice_message.wav',
    icon: 'audio',
    id: 100,
  },
];
