export const textSizeMap: Record<string, number> = {
  'text-xs': 12,
  'text-sm': 14,
  'text-base': 16,
  'text-lg': 18,
  'text-xl': 20,
  'text-2xl': 24,
  'text-3xl': 30,
  'text-4xl': 36,
  'text-5xl': 48,
};

export const FILTER_TABS: string[] = ['All', 'Files', 'People', 'Chats', 'Lists'];

export type LinkTabData = {
  filter: 'Files' | 'People' | 'Chats' | 'Lists';
  heading: string;
  subheading: string[];
  href: string;
  icon: string;
  status?: 'active' | 'inactive' | 'warning';
};

const peopleLinks = [
  'https://www.svgrepo.com/show/428259/matureman1.svg',
  'https://www.svgrepo.com/show/428256/malecostume.svg',
  'https://www.svgrepo.com/show/428260/maturewoman.svg',
  'https://www.svgrepo.com/show/428258/girl.svg',
  'https://www.svgrepo.com/show/428261/matureman2.svg',
  'https://www.svgrepo.com/show/428264/supportmale.svg',
  'https://www.svgrepo.com/show/428262/supportfemale.svg',
  'https://www.svgrepo.com/show/428269/female.svg',
  'https://www.svgrepo.com/show/428270/boy.svg',
];

export const FILTER_DATA: LinkTabData[] = [
  {
    filter: 'People',
    heading: 'Caroline A. Dribsson',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleLinks[0],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Adam Cadribean',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleLinks[1],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'James E. Watson',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[2],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Maria Gonzalez',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[3],
    status: 'active',
  },
  { filter: 'People', heading: 'John', subheading: ['Online'], href: '#', icon: peopleLinks[4], status: 'active' },
  {
    filter: 'People',
    heading: 'Sophia M. Taylor',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleLinks[5],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Michael Brown',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleLinks[6],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Isabella Lopez',
    subheading: ['Offline'],
    href: '#',
    icon: peopleLinks[7],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'William D. Smith',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[8],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Mia Johnson',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleLinks[0],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'David R. Garcia',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleLinks[1],
    status: 'warning',
  },
  { filter: 'People', heading: 'Olivia', subheading: ['Busy'], href: '#', icon: peopleLinks[2], status: 'warning' },
  {
    filter: 'People',
    heading: 'Richard Moore',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[3],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Emily Davis',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[4],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Joseph Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleLinks[5],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Amelia Clark',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleLinks[6],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Charles Wilkinson',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleLinks[7],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Evelyn Anderson',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[8],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Thomas Rodriguez',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[0],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Abigail Wilson',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[1],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Liam Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleLinks[2],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Noah Lopez',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleLinks[3],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Emma Johnson',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[4],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Oliver Davis',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[5],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Amelia Smith',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[6],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Elijah Garcia',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleLinks[7],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Mason R. Brown',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleLinks[8],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Logan Smith',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[0],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Ella Wilson',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[1],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Ava Johnson',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleLinks[2],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'James T. Miller',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[3],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Victoria P. Sanchez',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[4],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Benjamin Reid',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[5],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Chloe Martinez',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleLinks[6],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Zachary C. Evans',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleLinks[7],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Natalie King',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleLinks[8],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Samuel P. Torres',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[0],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Lily Foster',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[1],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Jack R. Bell',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[2],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Maddison O. Gray',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleLinks[3],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Henry Black',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleLinks[4],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Hannah S. White',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[5],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Sebastian Collins',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[6],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Zoe Davis',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[7],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Caleb Murphy',
    subheading: ['Unactivated'],
    href: '#',
    icon: peopleLinks[8],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Ella M. Morgan',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[0],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Jackson Perry',
    subheading: ['Active 4m ago'],
    href: '#',
    icon: peopleLinks[1],
    status: 'warning',
  },
  { filter: 'People', heading: 'Grace Long', subheading: ['Busy'], href: '#', icon: peopleLinks[2], status: 'warning' },
  {
    filter: 'People',
    heading: 'David Reed',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[3],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Samantha Hughes',
    subheading: ['Inactive since last month'],
    href: '#',
    icon: peopleLinks[4],
    status: 'inactive',
  },
  {
    filter: 'People',
    heading: 'Owen Howard',
    subheading: ['Active 1w ago'],
    href: '#',
    icon: peopleLinks[5],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Aria Bennett',
    subheading: ['Busy'],
    href: '#',
    icon: peopleLinks[6],
    status: 'warning',
  },
  {
    filter: 'People',
    heading: 'Eli Brooks',
    subheading: ['Online'],
    href: '#',
    icon: peopleLinks[7],
    status: 'active',
  },
  {
    filter: 'People',
    heading: 'Maya Anderson',
    subheading: ['Available'],
    href: '#',
    icon: peopleLinks[8],
    status: 'active',
  },
];
